version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = false
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
displaydelight = true
rusticdelight = true
farmersdelight = true
extradelight = true
sophisticatedstorage = true
butchery = true
butchercraft = true
beautify = true
waystones = true
etched = true
refurbished_furniture = true
toms_storage = true
minecraft = true
