onCull = false
MaxEntityEntities = 128
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = ["minecraft:player"]
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = false
startTime = 39.051
Hud = true
HudRXTX = false
HudFPS = true
HudCPU = false
HudGPU = true
HudRAM = true
HudEntityCount = false
HudPlayerPos = false
HudServer = false
HudCameraTarget = false
Mood = false
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
UseAui = false
DeBug = true
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "TECHNICAL"
MinDistance = 5
EntityDistance = 64
TickPerformance = true
ParticlePerformance = false
EntityViewDebug = false
ParticleCountLimit = 16384
BlockBreakParticle = true
AsyncCompute = true
